version: "3"

services:
  app:
    build:
      dockerfile: .github/workflows/Dockerfile
#    volumes:
#      - .:/tmp/thephilosophyofshakespeare
    ports:
      - "8080:8080"
#    environment:
#      DEBUG: "Eleventy*"
