name: "Convert and upload"

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Install pandoc
      run: apt-get install pandoc
